### ISSUE TITLE
Notification on Windows 10 shows "New notification"

### ISSUE THREAD

**Issue by sylveon** [makotokato/toastnotification#5]
I don't know if it is specific to Threshold 2, but notifications that I get are always generic.

![capture](https://cloud.githubusercontent.com/assets/6440374/13999309/27a27990-f112-11e5-91bf-4952880712c8.PNG)

**Comment by makotokato** [comment]
This is fixed by v0.4

**Comment by Lupus590** [comment]
I'm running 0.4.1 and have this issue on Firefox 55.0.3

Firefox has an update so I will comment again once I can test this again.

Edit: Firefox 56.0 now, ~~will check once I figure out how to force a notification.~~
I believe the update fixed it, that or the (other) addon that should be sending the notifications  is not working
